networks:
  site:
    name: site

services:
  nginx:
    container_name: site_nginx
    image: nginx:latest
    ports:
      - 80:80
#      - 89:89
    volumes:
      - ./www:/var/www
      - ./docker/vhost.conf:/etc/nginx/conf.d/default.conf
    networks:
      - site
    depends_on:
      - php
  php:
    container_name: site_php
    build: docker/images/php83fpm
    volumes:
      - ./www:/var/www
      - ./docker/php.ini:/usr/local/etc/php/conf.d/php.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - site
    depends_on:
      - mysql
  mysql:
    container_name: site_mysql
    image: mysql:8.0
    volumes:
      - ./www:/var/www/
      - ./docker/mysql-data:/var/lib/mysql
      - ./docker/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_USER=site
      - MYSQL_PASSWORD=site
      - MYSQL_ROOT_PASSWORD=site
      - MYSQL_DATABASE=site
    command: [ "--default-authentication-plugin=caching_sha2_password" ]
    networks:
      - site
  phpmyadmin:
    container_name: site_phpmyadmin
    image: phpmyadmin:latest
    restart: always
    ports:
      - 1500:80
    environment:
      - PMA_HOST=site_mysql
      - UPLOAD_LIMIT=1000M
      - MEMORY_LIMIT=2569M
      - MAX_EXECUTION_TIME=9000
    networks:
      - site
    depends_on:
      - mysql